### ISSUE TITLE
UPDATE product 

### ISSUE THREAD

**Issue by FlorentinaCraciun** [SummerSchoolAcademy2022/SS-BackEnd#11]
**Context:** Create the functionality that allows to UPDATE the product 

**User Story:** **As a** user, **I want to** be able to update different fields in my application, **so that** I can also provide information back to the application

**Acceptance Criteria:**
**Sceanrio 1- Update product - 200 OK**

**GIVEN** a frontend app made a request to BE Platform
**AND** a call is made to PATCH /products/{productId} endpoint
**WHEN** the product has all the mandatory fields
**THEN** the platform will update the product in the database

**Scenario 2 - Update product - 400 Bad Request**

**GIVEN** a frontend app made a request to BE Platform
**AND** a call is made to PATCH /products/{productId} endpoint
**WHEN** the product hasn't all the mandatory fields
**THEN** the platform will return 400

**Sceanrio 3- Update product - 404 Not Request**

**GIVEN** a frontend app made a request to BE Platform
**AND** a call is made to PATCH /products/{productId} endpoint
**WHEN** the product doesn't exists in database
**THEN** the platform will return 404

**Comment by lcobzaru** [comment]
ataseaza te rog PR-ul la acest ticket
